In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd  

In [8]:
bankdata = pd.read_csv("./bill_authentication.csv") 
bankdata.shape

(1372, 5)

In [9]:
bankdata.head() 

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [10]:
X = bankdata.drop('Class', axis=1)  
y = bankdata['Class']

In [11]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [12]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='linear')  
svclassifier.fit(X_train, y_train)  
y_pred = svclassifier.predict(X_test)  

In [13]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))

[[143   1]
 [  1 130]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       144
           1       0.99      0.99      0.99       131

   micro avg       0.99      0.99      0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275



In [14]:
def import_iris():
    url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
    # Assign colum names to the dataset
    colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
    # Read dataset to pandas dataframe
    irisdata = pd.read_csv(url, names=colnames) 
    # process
    X = irisdata.drop('Class', axis=1)  
    y = irisdata['Class']  
    from sklearn.model_selection import train_test_split  
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [15]:
def plot_predictions(clf, axes):
    x0s = np.linspace(axes[0], axes[1], 100)
    x1s = np.linspace(axes[2], axes[3], 100)
    x0, x1 = np.meshgrid(x0s, x1s)
    X = np.c_[x0.ravel(), x1.ravel()]
    y_pred = clf.predict(X).reshape(x0.shape)
    y_decision = clf.decision_function(X).reshape(x0.shape)
    plt.contourf(x0, x1, y_pred, cmap=plt.cm.brg, alpha=0.2)
    plt.contourf(x0, x1, y_decision, cmap=plt.cm.brg, alpha=0.1)



In [16]:
def polynomial_kernel():
    from sklearn.svm import SVC 
    pkclassifier = SVC(kernel='poly', degree = 8)  
    pkclassifier.fit(X_train, y_train)  
    y_pred_pk = pkclassifier.predict(X_test) 
    from sklearn.metrics import classification_report, confusion_matrix 
    print("Using Polynomial Kernal:")
    print(confusion_matrix(y_test,y_pred_pk))  
    print(classification_report(y_test,y_pred_pk))
    
    

In [17]:
def gaussian_kernel():
    from sklearn.svm import SVC  
    gclassifier = SVC(kernel='rbf')  
    gclassifier.fit(X_train, y_train)  
    y_pred_g = gclassifier.predict(X_test) 
    from sklearn.metrics import classification_report, confusion_matrix  
    print("Using Gaussian Kernel:")
    print(confusion_matrix(y_test,y_pred_g))  
    print(classification_report(y_test,y_pred_g))


In [18]:
def sigmoid_kernel():

    from sklearn.svm import SVC  
    sclassifier = SVC(kernel='sigmoid')  
    sclassifier.fit(X_train, y_train)  
    y_pred_s = sclassifier.predict(X_test) 
    from sklearn.metrics import classification_report, confusion_matrix  
    print("Using Sigmoid Kernel:")
    print(confusion_matrix(y_test,y_pred_s))  
    print(classification_report(y_test,y_pred_s))

In [19]:
def test():

    import_iris()

    polynomial_kernel()

    gaussian_kernel()

    sigmoid_kernel()

In [20]:
test()

c:\users\shubham bhadra\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


Using Polynomial Kernal:
[[138   6]
 [  0 131]]
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       144
           1       0.96      1.00      0.98       131

   micro avg       0.98      0.98      0.98       275
   macro avg       0.98      0.98      0.98       275
weighted avg       0.98      0.98      0.98       275

Using Gaussian Kernel:
[[144   0]
 [  0 131]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       144
           1       1.00      1.00      1.00       131

   micro avg       1.00      1.00      1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275

Using Sigmoid Kernel:
[[113  31]
 [ 27 104]]
              precision    recall  f1-score   support

           0       0.81      0.78      0.80       144
           1       0.77      0.79      0.78       131

   micro avg       0.79      0.79      0.79

c:\users\shubham bhadra\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
c:\users\shubham bhadra\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
